In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

In [3]:
train=pd.read_csv("train.csv")
# test=pd.read_csv("test.csv")

In [5]:
# getting all cols
train.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [6]:
#dropping the dependent colum for x and adding to y(col which we have to rpedict)
X_train=train.drop(columns=['SalePrice'])
y_train=train['SalePrice']

In [7]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [9]:
#getting null values
isnull_sum=X_train.isnull().sum()
isnull_sum

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType          8
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFin

In [10]:
#getting numeric cols only
num_vars=X_train.select_dtypes(include=['int64','float64']).columns
#getting numeric cols which have missing values
num_var_miss=[var for var in num_vars if isnull_sum[var]>0]

In [11]:
#printing numeric missing cols
num_var_miss

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [12]:
#getting categoric cols only
cat_vars=X_train.select_dtypes(include=['object']).columns
#getting categoric cols which have missing values
cat_var_miss=[var for var in cat_vars if isnull_sum[var]>0]

In [14]:
# printing categoric missing cols
cat_var_miss

['Alley',
 'MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

In [15]:
# we have to apply mean on this col
num_var_mean=['LotFrontage']
# we have to apply median on this col
num_var_median=[ 'MasVnrArea', 'GarageYrBlt']
# we have to apply mode on this col
cat_var_mode=['Alley',
 'MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu']
# we have to apply constant(missing) on this col
cat_var_missing=['GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

In [16]:
# create pipelines for each
num_var_mean_imputer=Pipeline(steps=[('imputer',SimpleImputer(strategy="mean"))])
num_var_median_imputer=Pipeline(steps=[('imputer',SimpleImputer(strategy="median"))])
cat_var_mode_imputer=Pipeline(steps=[('imputer',SimpleImputer(strategy="most_frequent"))])
cat_var_missing_imputer=Pipeline(steps=[('imputer',SimpleImputer(strategy="constant",fill_value="missing"))])

In [17]:
# create transformer
preprocessor=ColumnTransformer(transformers=[("mean_imputer",num_var_mean_imputer,num_var_mean),
                                ("median_imputer",num_var_median_imputer,num_var_median),
                                ("mode_imputer",cat_var_mode_imputer,cat_var_mode),
                                ("missing_imputer",cat_var_missing_imputer,cat_var_missing)])

In [18]:
# feeding data
preprocessor.fit(X_train)

ColumnTransformer(transformers=[('mean_imputer',
                                 Pipeline(steps=[('imputer', SimpleImputer())]),
                                 ['LotFrontage']),
                                ('median_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median'))]),
                                 ['MasVnrArea', 'GarageYrBlt']),
                                ('mode_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent'))]),
                                 ['Alley', 'MasVnrType', 'BsmtQual', 'BsmtCond',
                                  'BsmtExposure', 'BsmtFinType1',
                                  'BsmtFinType2', 'Electrical',
                                  'FireplaceQu']),
                                ('missing_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant'))]),
                                 ['GarageType', 'GarageFinish', 'GarageQual',
                                  'GarageCond', 'PoolQC', 'Fence',
                                  'MiscFeature'])])

In [19]:
preprocessor.transform

<bound method ColumnTransformer.transform of ColumnTransformer(transformers=[('mean_imputer',
                                 Pipeline(steps=[('imputer', SimpleImputer())]),
                                 ['LotFrontage']),
                                ('median_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median'))]),
                                 ['MasVnrArea', 'GarageYrBlt']),
                                ('mode_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent'))]),
                                 ['Alley', 'MasVnrType', 'BsmtQual', 'BsmtCond',
                                  'BsmtExposure', 'BsmtFinType1',
                                  'BsmtFinType2', 'Electrical',
                                  'FireplaceQu']),
                                ('missing_imputer',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant'))]),
                                 ['GarageType', 'GarageFinish', 'GarageQual',
                                  'GarageCond', 'PoolQC', 'Fence',
                                  'MiscFeature'])])>

In [21]:
# getting mean
preprocessor.named_transformers_['mean_imputer'].named_steps['imputer'].statistics_

array([70.04995837])

In [22]:
# checking mean with normal mean method()
X_train['LotFrontage'].mean()

70.04995836802665

In [23]:
# getting median
preprocessor.named_transformers_['median_imputer'].named_steps['imputer'].statistics_

array([   0., 1980.])

In [25]:
# checking median with median method()
X_train['MasVnrArea'].median()

1980.0

In [26]:
# checking median with median method()
X_train['GarageYrBlt'].median()

1980.0

In [36]:
# retruns an array
X_train_clean=preprocessor.transform(X_train)
X_train_clean

array([[65.0, 196.0, 2003.0, ..., 'missing', 'missing', 'missing'],
       [80.0, 0.0, 1976.0, ..., 'missing', 'missing', 'missing'],
       [68.0, 162.0, 2001.0, ..., 'missing', 'missing', 'missing'],
       ...,
       [66.0, 0.0, 1941.0, ..., 'missing', 'GdPrv', 'Shed'],
       [68.0, 0.0, 1950.0, ..., 'missing', 'missing', 'missing'],
       [75.0, 0.0, 1965.0, ..., 'missing', 'missing', 'missing']],
      dtype=object)

In [37]:
# creating a DataFrame
X_train_cleaned=pd.DataFrame(X_train_clean,columns=num_var_mean+num_var_median+cat_var_mode+cat_var_missing)
X_train_cleaned.head()

LotFrontage MasVnrArea GarageYrBlt Alley MasVnrType BsmtQual BsmtCond  \
0        65.0      196.0      2003.0  Grvl    BrkFace       Gd       TA   
1        80.0        0.0      1976.0  Grvl       None       Gd       TA   
2        68.0      162.0      2001.0  Grvl    BrkFace       Gd       TA   
3        60.0        0.0      1998.0  Grvl       None       TA       Gd   
4        84.0      350.0      2000.0  Grvl    BrkFace       Gd       TA   

  BsmtExposure BsmtFinType1 BsmtFinType2 Electrical FireplaceQu GarageType  \
0           No          GLQ          Unf      SBrkr          Gd     Attchd   
1           Gd          ALQ          Unf      SBrkr          TA     Attchd   
2           Mn          GLQ          Unf      SBrkr          TA     Attchd   
3           No          ALQ          Unf      SBrkr          Gd     Detchd   
4           Av          GLQ          Unf      SBrkr          TA     Attchd   

  GarageFinish GarageQual GarageCond   PoolQC    Fence MiscFeature  
0          RFn         TA         TA  missing  missing     missing  
1          RFn         TA         TA  missing  missing     missing  
2          RFn         TA         TA  missing  missing     missing  
3          Unf         TA         TA  missing  missing     missing  
4          RFn         TA         TA  missing  missing     missing

In [39]:
# chceking if any null value is there
X_train_cleaned.isnull().sum()

LotFrontage     0
MasVnrArea      0
GarageYrBlt     0
Alley           0
MasVnrType      0
BsmtQual        0
BsmtCond        0
BsmtExposure    0
BsmtFinType1    0
BsmtFinType2    0
Electrical      0
FireplaceQu     0
GarageType      0
GarageFinish    0
GarageQual      0
GarageCond      0
PoolQC          0
Fence           0
MiscFeature     0
dtype: int64